### ISSUE TITLE
what about FIQL?

### ISSUE THREAD

**Issue by dret** [philsturgeon/tech-talks#4]
if you're really into history and all that, what about mentioning @mnot's FIQL? https://tools.ietf.org/html/draft-nottingham-atompub-fiql-00
it was an early attempt to query into shared data models. it's different in that the model it's built for is more fixed. it's similar in that it tries to cater to the fact that different clients want to know about different aspects of web resources, and ideally they can all get exactly what they want.

**Comment by philsturgeon** [comment]
Awesome! I'll do that, thank you. I want a whole bit on "If the API worlds problems were going to be solved by a QL, why were none of these popular" and I'll throw that in there. A push back against OMFG THIS NEW IDEA.

**Comment by philsturgeon** [comment]
Closed in 01f44b96
